var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = { "classes" : [
    {"id" : 3923, "sl" : 15, "el" : 302, "name" : "RecordStateMethodCallMissingTest",
    "methods" : [
              {"sl" : 20, "el" : 24, "sc" : 5},  {"sl" : 26, "el" : 36, "sc" : 5},  {"sl" : 38, "el" : 48, "sc" : 5},  {"sl" : 50, "el" : 60, "sc" : 5},  {"sl" : 62, "el" : 72, "sc" : 5},  {"sl" : 74, "el" : 84, "sc" : 5},  {"sl" : 86, "el" : 96, "sc" : 5},  {"sl" : 98, "el" : 108, "sc" : 5},  {"sl" : 110, "el" : 120, "sc" : 5},  {"sl" : 122, "el" : 132, "sc" : 5},  {"sl" : 134, "el" : 144, "sc" : 5},  {"sl" : 146, "el" : 156, "sc" : 5},  {"sl" : 158, "el" : 168, "sc" : 5},  {"sl" : 170, "el" : 180, "sc" : 5},  {"sl" : 182, "el" : 192, "sc" : 5},  {"sl" : 194, "el" : 204, "sc" : 5},  {"sl" : 206, "el" : 216, "sc" : 5},  {"sl" : 218, "el" : 228, "sc" : 5},  {"sl" : 230, "el" : 240, "sc" : 5},  {"sl" : 242, "el" : 252, "sc" : 5},  {"sl" : 254, "el" : 264, "sc" : 5},  {"sl" : 266, "el" : 276, "sc" : 5},  {"sl" : 278, "el" : 288, "sc" : 5},  {"sl" : 290, "el" : 300, "sc" : 5}  ]}
    
 ]
};

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {
		"test_412" : {
					  "name" : "setLongReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 38 },],
					  "statements" : [{"sl": 40 },{"sl": 41 },{"sl": 44 },]
					  },
		"test_357" : {
					  "name" : "asStubWithNonVoidMethod",
					  "pass" : true ,
					  "methods" : [{"sl": 290 },],
					  "statements" : [{"sl": 292 },{"sl": 293 },{"sl": 294 },{"sl": 297 },]
					  },
		"test_395" : {
					  "name" : "setFloatDefaultReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 218 },],
					  "statements" : [{"sl": 220 },{"sl": 221 },{"sl": 224 },]
					  },
		"test_399" : {
					  "name" : "setDefaultThrowableWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 266 },],
					  "statements" : [{"sl": 268 },{"sl": 269 },{"sl": 272 },]
					  },
		"test_390" : {
					  "name" : "setBooleanDefaultReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 194 },],
					  "statements" : [{"sl": 196 },{"sl": 197 },{"sl": 200 },]
					  },
		"test_397" : {
					  "name" : "setObjectDefaultReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 242 },],
					  "statements" : [{"sl": 244 },{"sl": 245 },{"sl": 248 },]
					  },
		"test_418" : {
					  "name" : "setObjectReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 74 },],
					  "statements" : [{"sl": 76 },{"sl": 77 },{"sl": 80 },]
					  },
		"test_387" : {
					  "name" : "setObjectReturnValueCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 158 },],
					  "statements" : [{"sl": 160 },{"sl": 161 },{"sl": 164 },]
					  },
		"test_429" : {
					  "name" : "setThrowableWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 98 },],
					  "statements" : [{"sl": 100 },{"sl": 101 },{"sl": 104 },]
					  },
		"test_402" : {
					  "name" : "timesWithoutReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 278 },],
					  "statements" : [{"sl": 280 },{"sl": 281 },{"sl": 282 },{"sl": 285 },]
					  },
		"test_389" : {
					  "name" : "setThrowableCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 182 },],
					  "statements" : [{"sl": 184 },{"sl": 185 },{"sl": 188 },]
					  },
		"test_385" : {
					  "name" : "setDoubleReturnValueCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 146 },],
					  "statements" : [{"sl": 148 },{"sl": 149 },{"sl": 152 },]
					  },
		"test_427" : {
					  "name" : "setBooleanReturnValueCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 110 },],
					  "statements" : [{"sl": 112 },{"sl": 113 },{"sl": 116 },]
					  },
		"test_383" : {
					  "name" : "setFloatReturnValueCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 134 },],
					  "statements" : [{"sl": 136 },{"sl": 137 },{"sl": 140 },]
					  },
		"test_423" : {
					  "name" : "setLongReturnValueCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 122 },],
					  "statements" : [{"sl": 124 },{"sl": 125 },{"sl": 128 },]
					  },
		"test_393" : {
					  "name" : "setLongDefaultReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 206 },],
					  "statements" : [{"sl": 208 },{"sl": 209 },{"sl": 212 },]
					  },
		"test_420" : {
					  "name" : "setDoubleReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 62 },],
					  "statements" : [{"sl": 64 },{"sl": 65 },{"sl": 68 },]
					  },
		"test_398" : {
					  "name" : "setDefaultVoidCallableWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 254 },],
					  "statements" : [{"sl": 256 },{"sl": 257 },{"sl": 260 },]
					  },
		"test_422" : {
					  "name" : "setFloatReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 50 },],
					  "statements" : [{"sl": 52 },{"sl": 53 },{"sl": 56 },]
					  },
		"test_388" : {
					  "name" : "setVoidCallableCountWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 170 },],
					  "statements" : [{"sl": 172 },{"sl": 173 },{"sl": 176 },]
					  },
		"test_396" : {
					  "name" : "setDoubleDefaultReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 230 },],
					  "statements" : [{"sl": 232 },{"sl": 233 },{"sl": 236 },]
					  },
		"test_416" : {
					  "name" : "setVoidCallableWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 86 },],
					  "statements" : [{"sl": 88 },{"sl": 89 },{"sl": 92 },]
					  },
		"test_413" : {
					  "name" : "setBooleanReturnValueWithoutMethodCall",
					  "pass" : true ,
					  "methods" : [{"sl": 26 },],
					  "statements" : [{"sl": 28 },{"sl": 29 },{"sl": 32 },]
					  }
 };

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [  [],   [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 413   ] ,
  [  ] ,
  [ 413   ] ,
  [ 413   ] ,
  [  ] ,
  [  ] ,
  [ 413   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 412   ] ,
  [  ] ,
  [ 412   ] ,
  [ 412   ] ,
  [  ] ,
  [  ] ,
  [ 412   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 422   ] ,
  [  ] ,
  [ 422   ] ,
  [ 422   ] ,
  [  ] ,
  [  ] ,
  [ 422   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 420   ] ,
  [  ] ,
  [ 420   ] ,
  [ 420   ] ,
  [  ] ,
  [  ] ,
  [ 420   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 418   ] ,
  [  ] ,
  [ 418   ] ,
  [ 418   ] ,
  [  ] ,
  [  ] ,
  [ 418   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 416   ] ,
  [  ] ,
  [ 416   ] ,
  [ 416   ] ,
  [  ] ,
  [  ] ,
  [ 416   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 429   ] ,
  [  ] ,
  [ 429   ] ,
  [ 429   ] ,
  [  ] ,
  [  ] ,
  [ 429   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 427   ] ,
  [  ] ,
  [ 427   ] ,
  [ 427   ] ,
  [  ] ,
  [  ] ,
  [ 427   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 423   ] ,
  [  ] ,
  [ 423   ] ,
  [ 423   ] ,
  [  ] ,
  [  ] ,
  [ 423   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 383   ] ,
  [  ] ,
  [ 383   ] ,
  [ 383   ] ,
  [  ] ,
  [  ] ,
  [ 383   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 385   ] ,
  [  ] ,
  [ 385   ] ,
  [ 385   ] ,
  [  ] ,
  [  ] ,
  [ 385   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 387   ] ,
  [  ] ,
  [ 387   ] ,
  [ 387   ] ,
  [  ] ,
  [  ] ,
  [ 387   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 388   ] ,
  [  ] ,
  [ 388   ] ,
  [ 388   ] ,
  [  ] ,
  [  ] ,
  [ 388   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 389   ] ,
  [  ] ,
  [ 389   ] ,
  [ 389   ] ,
  [  ] ,
  [  ] ,
  [ 389   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 390   ] ,
  [  ] ,
  [ 390   ] ,
  [ 390   ] ,
  [  ] ,
  [  ] ,
  [ 390   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 393   ] ,
  [  ] ,
  [ 393   ] ,
  [ 393   ] ,
  [  ] ,
  [  ] ,
  [ 393   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 395   ] ,
  [  ] ,
  [ 395   ] ,
  [ 395   ] ,
  [  ] ,
  [  ] ,
  [ 395   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 396   ] ,
  [  ] ,
  [ 396   ] ,
  [ 396   ] ,
  [  ] ,
  [  ] ,
  [ 396   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 397   ] ,
  [  ] ,
  [ 397   ] ,
  [ 397   ] ,
  [  ] ,
  [  ] ,
  [ 397   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 398   ] ,
  [  ] ,
  [ 398   ] ,
  [ 398   ] ,
  [  ] ,
  [  ] ,
  [ 398   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 399   ] ,
  [  ] ,
  [ 399   ] ,
  [ 399   ] ,
  [  ] ,
  [  ] ,
  [ 399   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 402   ] ,
  [  ] ,
  [ 402   ] ,
  [ 402   ] ,
  [ 402   ] ,
  [  ] ,
  [  ] ,
  [ 402   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 357   ] ,
  [  ] ,
  [ 357   ] ,
  [ 357   ] ,
  [ 357   ] ,
  [  ] ,
  [  ] ,
  [ 357   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] 
];
