var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = { "classes" : [
    {"id" : 1648, "sl" : 14, "el" : 147, "name" : "RecordStateInvalidReturnValueTest",
    "methods" : [
              {"sl" : 19, "el" : 23, "sc" : 5},  {"sl" : 25, "el" : 35, "sc" : 5},  {"sl" : 37, "el" : 46, "sc" : 5},  {"sl" : 48, "el" : 57, "sc" : 5},  {"sl" : 59, "el" : 68, "sc" : 5},  {"sl" : 70, "el" : 79, "sc" : 5},  {"sl" : 81, "el" : 91, "sc" : 5},  {"sl" : 93, "el" : 102, "sc" : 5},  {"sl" : 104, "el" : 113, "sc" : 5},  {"sl" : 115, "el" : 124, "sc" : 5},  {"sl" : 126, "el" : 135, "sc" : 5},  {"sl" : 137, "el" : 146, "sc" : 5}  ]}
    
 ]
};

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {
		"test_339" : {
					  "name" : "setInvalidBooleanReturnValueCount",
					  "pass" : true ,
					  "methods" : [{"sl": 81 },],
					  "statements" : [{"sl": 83 },{"sl": 84 },{"sl": 85 },{"sl": 88 },]
					  },
		"test_340" : {
					  "name" : "setInvalidFloatReturnValueCount",
					  "pass" : true ,
					  "methods" : [{"sl": 104 },],
					  "statements" : [{"sl": 106 },{"sl": 107 },{"sl": 108 },{"sl": 111 },]
					  },
		"test_331" : {
					  "name" : "setInvalidDoubleReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 59 },],
					  "statements" : [{"sl": 61 },{"sl": 62 },{"sl": 63 },{"sl": 66 },]
					  },
		"test_277" : {
					  "name" : "setInvalidBooleanReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 25 },],
					  "statements" : [{"sl": 27 },{"sl": 28 },{"sl": 29 },{"sl": 32 },]
					  },
		"test_274" : {
					  "name" : "setInvalidLongReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 37 },],
					  "statements" : [{"sl": 39 },{"sl": 40 },{"sl": 41 },{"sl": 44 },]
					  },
		"test_344" : {
					  "name" : "setReturnValueForVoidMethod",
					  "pass" : true ,
					  "methods" : [{"sl": 137 },],
					  "statements" : [{"sl": 139 },{"sl": 140 },{"sl": 141 },{"sl": 144 },]
					  },
		"test_336" : {
					  "name" : "setInvalidObjectReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 70 },],
					  "statements" : [{"sl": 72 },{"sl": 73 },{"sl": 74 },{"sl": 77 },]
					  },
		"test_343" : {
					  "name" : "setInvalidDoubleReturnValueCount",
					  "pass" : true ,
					  "methods" : [{"sl": 115 },],
					  "statements" : [{"sl": 117 },{"sl": 118 },{"sl": 119 },{"sl": 122 },]
					  },
		"test_345" : {
					  "name" : "setInvalidObjectReturnValueCount",
					  "pass" : true ,
					  "methods" : [{"sl": 126 },],
					  "statements" : [{"sl": 128 },{"sl": 129 },{"sl": 130 },{"sl": 133 },]
					  },
		"test_337" : {
					  "name" : "setInvalidLongReturnValueCount",
					  "pass" : true ,
					  "methods" : [{"sl": 93 },],
					  "statements" : [{"sl": 95 },{"sl": 96 },{"sl": 97 },{"sl": 100 },]
					  },
		"test_276" : {
					  "name" : "setInvalidFloatReturnValue",
					  "pass" : true ,
					  "methods" : [{"sl": 48 },],
					  "statements" : [{"sl": 50 },{"sl": 51 },{"sl": 52 },{"sl": 55 },]
					  }
 };

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [  [],   [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 277   ] ,
  [  ] ,
  [ 277   ] ,
  [ 277   ] ,
  [ 277   ] ,
  [  ] ,
  [  ] ,
  [ 277   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 274   ] ,
  [  ] ,
  [ 274   ] ,
  [ 274   ] ,
  [ 274   ] ,
  [  ] ,
  [  ] ,
  [ 274   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 276   ] ,
  [  ] ,
  [ 276   ] ,
  [ 276   ] ,
  [ 276   ] ,
  [  ] ,
  [  ] ,
  [ 276   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 331   ] ,
  [  ] ,
  [ 331   ] ,
  [ 331   ] ,
  [ 331   ] ,
  [  ] ,
  [  ] ,
  [ 331   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 336   ] ,
  [  ] ,
  [ 336   ] ,
  [ 336   ] ,
  [ 336   ] ,
  [  ] ,
  [  ] ,
  [ 336   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 339   ] ,
  [  ] ,
  [ 339   ] ,
  [ 339   ] ,
  [ 339   ] ,
  [  ] ,
  [  ] ,
  [ 339   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 337   ] ,
  [  ] ,
  [ 337   ] ,
  [ 337   ] ,
  [ 337   ] ,
  [  ] ,
  [  ] ,
  [ 337   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 340   ] ,
  [  ] ,
  [ 340   ] ,
  [ 340   ] ,
  [ 340   ] ,
  [  ] ,
  [  ] ,
  [ 340   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 343   ] ,
  [  ] ,
  [ 343   ] ,
  [ 343   ] ,
  [ 343   ] ,
  [  ] ,
  [  ] ,
  [ 343   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 345   ] ,
  [  ] ,
  [ 345   ] ,
  [ 345   ] ,
  [ 345   ] ,
  [  ] ,
  [  ] ,
  [ 345   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 344   ] ,
  [  ] ,
  [ 344   ] ,
  [ 344   ] ,
  [ 344   ] ,
  [  ] ,
  [  ] ,
  [ 344   ] ,
  [  ] ,
  [  ] ,
  [  ] 
];
