var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = { "classes" : [
    {"id" : 1723, "sl" : 17, "el" : 106, "name" : "UsageRangeTest",
    "methods" : [
              {"sl" : 23, "el" : 28, "sc" : 5},  {"sl" : 30, "el" : 36, "sc" : 5},  {"sl" : 38, "el" : 45, "sc" : 5},  {"sl" : 47, "el" : 56, "sc" : 5},  {"sl" : 58, "el" : 95, "sc" : 5},  {"sl" : 97, "el" : 105, "sc" : 5}  ]}
    
 ]
};

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {
		"test_346" : {
					  "name" : "zeroOrMoreNoCalls",
					  "pass" : true ,
					  "methods" : [{"sl": 30 },],
					  "statements" : [{"sl": 32 },{"sl": 33 },{"sl": 34 },{"sl": 35 },]
					  },
		"test_319" : {
					  "name" : "zeroOrMoreThreeCalls",
					  "pass" : true ,
					  "methods" : [{"sl": 47 },],
					  "statements" : [{"sl": 49 },{"sl": 50 },{"sl": 51 },{"sl": 52 },{"sl": 53 },{"sl": 54 },{"sl": 55 },]
					  },
		"test_314" : {
					  "name" : "zeroOrMoreOneCall",
					  "pass" : true ,
					  "methods" : [{"sl": 38 },],
					  "statements" : [{"sl": 40 },{"sl": 41 },{"sl": 42 },{"sl": 43 },{"sl": 44 },]
					  },
		"test_329" : {
					  "name" : "withIllegalOwnRange",
					  "pass" : true ,
					  "methods" : [{"sl": 97 },],
					  "statements" : [{"sl": 99 },{"sl": 100 },{"sl": 101 },{"sl": 103 },]
					  },
		"test_308" : {
					  "name" : "combination",
					  "pass" : true ,
					  "methods" : [{"sl": 58 },],
					  "statements" : [{"sl": 60 },{"sl": 61 },{"sl": 62 },{"sl": 63 },{"sl": 65 },{"sl": 66 },{"sl": 67 },{"sl": 68 },{"sl": 70 },{"sl": 71 },{"sl": 73 },{"sl": 75 },{"sl": 76 },{"sl": 77 },{"sl": 79 },{"sl": 81 },{"sl": 82 },{"sl": 87 },{"sl": 89 },{"sl": 91 },{"sl": 93 },]
					  }
 };

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [  [],   [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 346   ] ,
  [  ] ,
  [ 346   ] ,
  [ 346   ] ,
  [ 346   ] ,
  [ 346   ] ,
  [  ] ,
  [  ] ,
  [ 314   ] ,
  [  ] ,
  [ 314   ] ,
  [ 314   ] ,
  [ 314   ] ,
  [ 314   ] ,
  [ 314   ] ,
  [  ] ,
  [  ] ,
  [ 319   ] ,
  [  ] ,
  [ 319   ] ,
  [ 319   ] ,
  [ 319   ] ,
  [ 319   ] ,
  [ 319   ] ,
  [ 319   ] ,
  [ 319   ] ,
  [  ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [ 308   ] ,
  [ 308   ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [ 308   ] ,
  [ 308   ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [ 308   ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [ 308   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [ 308   ] ,
  [  ] ,
  [  ] ,
  [  ] ,
  [ 329   ] ,
  [  ] ,
  [ 329   ] ,
  [ 329   ] ,
  [ 329   ] ,
  [  ] ,
  [ 329   ] ,
  [  ] ,
  [  ] ,
  [  ] 
];
